changelog:
  exclude:
    labels: [duplicate, invalid, wontfix]
  categories:
    - title: Fixes
      labels: [bug]
    - title: Improvements
      labels: [enhancement, accessibility]
    - title: Documentation
      labels: [documentation]
    - title: Other changes
      labels: ["*"]
